import { useState } from 'react';
import { X, Download, FileCode, Archive } from 'lucide-react';
import JSZip from 'jszip';
import { useProjectStore } from '../../store/useProjectStore';
import { generateFullCode } from '../../engine/codeGenerator';
import { generateStandaloneHTML } from '../../engine/htmlGenerator';

interface Props {
  onClose: () => void;
}

export default function Exporter({ onClose }: Props) {
  const formSettings = useProjectStore((s) => s.formSettings);
  const components = useProjectStore((s) => s.components);
  const eventHandlers = useProjectStore((s) => s.eventHandlers);
  const [building, setBuilding] = useState(false);

  const handleDownloadHTML = async () => {
    setBuilding(true);
    try {
      const html = generateStandaloneHTML(formSettings, components, eventHandlers);
      const blob = new Blob([html], { type: 'text/html' });
      downloadBlob(blob, `${formSettings.name}.html`);
    } finally {
      setBuilding(false);
    }
  };

  const handleDownloadZip = async () => {
    setBuilding(true);
    try {
      const html = generateStandaloneHTML(formSettings, components, eventHandlers);
      const vbCode = generateFullCode(formSettings, components, eventHandlers);

      const zip = new JSZip();
      zip.file('index.html', html);
      zip.file(`${formSettings.name}.vb`, vbCode);
      zip.file(
        'README.txt',
        `${formSettings.name}\n${'='.repeat(formSettings.name.length)}\n\nGenerated by VB.NET Visual Designer\n\nFiles:\n- index.html: Standalone web application\n- ${formSettings.name}.vb: VB.NET source code\n\nTo run: Open index.html in any modern web browser.\n`
      );

      const blob = await zip.generateAsync({ type: 'blob' });
      downloadBlob(blob, `${formSettings.name}.zip`);
    } finally {
      setBuilding(false);
    }
  };

  const handleExportVB = () => {
    const code = generateFullCode(formSettings, components, eventHandlers);
    const blob = new Blob([code], { type: 'text/plain' });
    downloadBlob(blob, `${formSettings.name}.vb`);
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-2xl w-[460px] overflow-hidden">
        <div className="bg-[#0078D4] px-4 py-3 flex items-center justify-between">
          <span className="text-white text-sm font-medium">Build & Export</span>
          <button onClick={onClose} className="text-white/70 hover:text-white">
            <X size={16} />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div className="text-sm text-[#444]">
            <span className="font-medium text-[#1E1E1E]">{formSettings.name}</span>
            <span className="text-[#888] ml-2">
              {components.length} component{components.length !== 1 ? 's' : ''}
            </span>
          </div>

          <div className="space-y-2">
            <button
              onClick={handleDownloadHTML}
              disabled={building}
              className="w-full flex items-center gap-3 px-4 py-3 bg-[#F5F5F5] border border-[#E0E0E0] rounded hover:bg-[#EAEAEA] transition-colors text-left group"
            >
              <div className="w-10 h-10 rounded bg-[#0078D4] flex items-center justify-center flex-shrink-0">
                <Download size={18} className="text-white" />
              </div>
              <div>
                <div className="text-sm font-medium text-[#1E1E1E] group-hover:text-[#0078D4]">
                  Download Standalone HTML
                </div>
                <div className="text-xs text-[#888]">
                  Single .html file with embedded runtime
                </div>
              </div>
            </button>

            <button
              onClick={handleDownloadZip}
              disabled={building}
              className="w-full flex items-center gap-3 px-4 py-3 bg-[#F5F5F5] border border-[#E0E0E0] rounded hover:bg-[#EAEAEA] transition-colors text-left group"
            >
              <div className="w-10 h-10 rounded bg-[#107C10] flex items-center justify-center flex-shrink-0">
                <Archive size={18} className="text-white" />
              </div>
              <div>
                <div className="text-sm font-medium text-[#1E1E1E] group-hover:text-[#107C10]">
                  Download Full Package (.zip)
                </div>
                <div className="text-xs text-[#888]">
                  HTML app + VB.NET source + README
                </div>
              </div>
            </button>

            <button
              onClick={handleExportVB}
              className="w-full flex items-center gap-3 px-4 py-3 bg-[#F5F5F5] border border-[#E0E0E0] rounded hover:bg-[#EAEAEA] transition-colors text-left group"
            >
              <div className="w-10 h-10 rounded bg-[#5C2D91] flex items-center justify-center flex-shrink-0">
                <FileCode size={18} className="text-white" />
              </div>
              <div>
                <div className="text-sm font-medium text-[#1E1E1E] group-hover:text-[#5C2D91]">
                  Export VB.NET Source
                </div>
                <div className="text-xs text-[#888]">
                  Download {formSettings.name}.vb source file
                </div>
              </div>
            </button>
          </div>

          {building && (
            <div className="text-center py-2">
              <span className="text-xs text-[#0078D4]">Building...</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
